stages:
  - knit
  - release

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: "500"

.knit:
  stage: knit
  interruptible: true
  script:
    - |
      sudo apk add R texlive-full python3 py3-yaml py3-rpy2 py3-colorama ttf-liberation font-liberation font-liberation-mono-nerd font-liberation-sans-narrow
      sudo PYTHONUNBUFFERED=true LD_LIBRARY_PATH=/usr/lib/R/lib ./.gitlab/bin/install-packages.py
      R -e "bookdown::render_book('index.Rmd')"
      echo "JOB_ID=$CI_JOB_ID" > job.env
  artifacts:
    reports:
      dotenv: job.env
  tags:
    - knit

snapshot:knit:
  extends: .knit
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_ID
  after_script:
    - cp _book/*.pdf $CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA.pdf
  artifacts:
    paths:
      - $CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA.pdf
    expire_in: 7 days
    when: always

publish:knit: 
  extends: .knit
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /snapshot.*/
  after_script:
    - cp _book/*.pdf $CI_PROJECT_NAME-$CI_COMMIT_TAG.pdf
  artifacts:
    paths:
      - $CI_PROJECT_NAME-$CI_COMMIT_TAG.pdf
    expire_in: never
    when: always

snapshot:release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG || $CI_MERGE_REQUEST_ID
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  allow_failure: false
  tags:
    - knit
  when: on_success
  script:
    - echo "Create Release $CI_COMMIT_SHORT_SHA"
    - echo $JOB_ID
  release:
    name: 'Snapshot $CI_COMMIT_SHORT_SHA'
    description: '$CI_COMMIT_MESSAGE'
    tag_name: "snapshot-$CI_COMMIT_SHORT_SHA"
    ref: '$CI_COMMIT_SHA'
    assets:
      links:
        - name: "$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA.pdf"
          filepath: "/snapshot/$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA.pdf"
          url: "$CI_PROJECT_URL/-/jobs/$JOB_ID/artifacts/raw/$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA.pdf"

publish:release:
  stage: release
  allow_failure: false
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /snapshot.*/
  tags:
    - knit
  when: on_success
  script:
    - echo "Create Release $CI_COMMIT_TAG"
    - echo $JOB_ID
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: '$CI_COMMIT_MESSAGE'
    tag_name: "$CI_COMMIT_TAG"
    ref: '$CI_COMMIT_SHA'
    assets:
      links:
        - name: "$CI_PROJECT_NAME-$CI_COMMIT_TAG.pdf"
          filepath: "/pdf/$CI_PROJECT_NAME-$CI_COMMIT_TAG.pdf"
          url: "$CI_PROJECT_URL/-/jobs/$JOB_ID/artifacts/raw/$CI_PROJECT_NAME-$CI_COMMIT_TAG.pdf"
