---
knit: bookdown::render_book
editor_options: 
  markdown: 
    wrap: 80
---

# Introduction / background

The COVID-19 pandemic has highlighted the vast ethnic, social, economic, and
health disparities in high-income countries, including Canada. One of the most
vulnerable segments of these affluent societies is the immigrant population,
that has become widely diversified with more and more people coming from
developing countries, and for whom integration into their new society may be
more difficult. The coronavirus pandemic brings a new challenge for these
immigrant populations, directly or indirectly through the tensions between the
ethnic groups that it helps to generate [@coates2020Covid19]. These immigrants
face language barriers, low social capital, housing insecurity, and severe
poverty, rendering them particularly susceptible to the effects of the current
pandemic. Immigrants are also more likely to be employed as essential workers
where social distancing, sanitary precautions, and self-isolation, measures put
in place to mitigate the pandemy, are challenging [@reid2021Migrant;
@yi2021Health; @zhang2021COVID19]. More importantly, migrants may encounter
various forms of discrimination, leading to social exclusion and restricted
access to healthcare and social services [@spiritus-beerden2021Mental]. It is
therefore necessary to understand how this pandemic affects these immigrant
populations differently and the native populations in Quebec. In doing so, this
article will reveal a better understanding of how the current pandemic
aggravates existing inequalities and challenges in the province for immigrants
and their descendants.

<!-- The province of Quebec has one of the highest concentrations of immigrants in Canada, including permanent residents, temporary residents, and refugees [@governmentofcanada2017Daily; @immigration2005Recent]. In 2016, 1.2 million immigrants were living in Quebec, an increase from 8% in 1990 to 13.7% of the population in 2016 (Institut de la statistique du Québec, 2020). <!--As of 2019, the increase in net new residents (60,700 versus 42,200 in 2018) and lower interprovincial migration losses (-1,500 versus -6,100 in 2018) contributed to Quebec's population growth. -->

Since the start of the pandemic, most of the confirmed cases were identified in
Montreal and areas with high immigrant populations [@miconi2021Ethnocultural;
@shields2020COVID19]. The coronavirus pandemic has infected nearly 450,000
people in Quebec and has resulted in more than 11,000 deaths
(<https://www.quebec.ca/sante/problemes-de-sante/a-z/coronavirus-2019/situation-coronavirus-quebec>,
consulted on octobre 29, 2021). This makes it the worst affected province in
Canada and one of the worst affected regions in the world during the first wave
of the pandemic. Although the majority of these deaths took place in elderly's
homes, and therefore affected more this segment of the population, its overall
influence on individuals is not to be overlooked. It has been shown that, on the
one hand, immigrants and their families have a higher risk of being exposed to
the pathogen, and, at the same time, they are more vulnerable to racism and
discrimination and face barriers to accessing social support [@2021CRARR] and
information, especially for those who didn't speak or understand the two
official langages.
<!--In addition to the direct consequences of the pandemic, the measures taken by various governments around the world are also not without consequences on families. -->Several
studies have thus shown excess mortality in ethnocultural minority populations
[@bertocchi2020Covid19], higher unemployment, greater loss of income and
negative consequences for children and families in several countries. This
differentiated effect can be explained in different ways. On the one hand, in
terms of the direct consequences of the pandemic, the situation of
precariousness and greater poverty among immigrants exposes them more to the
more harmful consequences of the disease on their state of health. Likewise,
immigrants often work in jobs where social distancing is difficult to enforce.
On the other hand, indirectly, the solutions to the crisis affect immigrants and
natives differently. The complete shutdown of tye economy with its set of
adjustments has greatly impeded the employability of immigrants, especially
newcomers who have not yet grasped the workings of society and who cannot
benefit from state subsidies. But, it is also shown that these effects are not
uniform on the whole of the immigrant population, itself, very diverse.

Despite the growing focus on the differential impacts of the COVID-19 on
immigrants and non-immigrants segment of the population, there is still very
little knowledge about how the pandemic and its related public policy impact the
lives of immigrants and their families. The existing health datasets (largely
used to assess this effect) are not necessarily representative of the immigrant
population and do not offer an accurate picture of the complex social status and
health outcomes among this group [@choi2021Studying; @gagnon2021Immigration;
@khan2015Visible]. In most cases, these datasets lack data on the residence
length of immigrants and combine newcomers with long-term settlers
[@edge2013Discrimination; @hayward2021Clinical]. As a result, they may not allow
a detailed assessment of the nature and extent of risk exposure in sub-segments
of populations, as well as whether interventions are reaching those most at
risk. In addition, the family-level impacts of the pandemic are still poorly
understood. While a body of research has explored the association between the
pandemic and its potential effects on intimate partner violence and marital
dissolution [@bhatnagar2021Navigating; @koshan2020COVID19; @morrison2021Chapter;
@prime2020Risk], few studies have examined negative familial repercussions in
the context of immigration status. There is ample evidence that sustained family
relationships greatly enhance immigrants' lives on several fronts, including
fostering economic prosperity [@marger2001Sociala], psychological well-being
[@beiser2002Povertya], social network development [@evansluong2017Familya], and
educational success for children [@munroe-blum1989Immigranta]. The family is,
therefore, a key component of long-term social mobility and economic success of
immigrants.

<!--Faced with the pandemic, the governments of Canada and Quebec have implemented a number of measures to reduce its impact. These policies can be broken down at two levels, direct support to families, including the Canadian Emergency Benefit, which can provide employees and self-employed workers affected by Covid-19 with a financial benefit of up to $ 2,000. On the other hand, the government supports many companies to keep their employees or supports them directly when the revenues from their activities have fallen considerably. While these measures allow families to cope better with the crisis, the fact remains that the changes brought about by this crisis can affect other dimensions of life. How these measures make a difference in the face of the pandemic remains to be seen. -->

Based on an original biographic survey collected around the first wave of the
pandemic in august-november 2020 on immigrants and the native population of
Québec, this study mainly aims to understand the family exposure, consequences,
and responses of the pandemic on immigrant and native Quebec populations. We
assess a whole range of different measures of each outcome. We divided the
consequences in three dimensions, 1) access to ressources, 2) ability to perform
duties and 3) employment and income. We seek also to analyse in what ways these
outcomes differ according to the immigrants length of residence. By doing so,
this study provide a clear and global picture of the situation of different
population groups in Quebec in the face of the COVID-19.
<!-- To respond to these questions, we will use data collected around the first wave of the pandemic in august-november 2020. Our study aims to fill the gap by analyzing group-specific differences in exposure risk, family consequences, and access to resources among immigrants and Quebecers. We also seek to shed light on several socio-cultural strategies to mitigate inequality and recommend relevant policy solutions. The detailed findings will help policymakers address health inequalities and improve equity in Quebec while developing adequate measures and programs. -->

<!-- Introduction  -->

<!-- Like the rest of Canada, Quebec has experienced a substantial increase in its immigration in recent years. The immigrant population in the province thus increased from 8% in the 1990s to 13.7% of the population, or 1.2 million individuals in 2016 (Institut de la statistique du Québec, 2020). This immigration is also unique in that it has become widely diversified with more and more people coming from developing countries, and for whom integration into their new society may be more difficult. The coronavirus pandemic brings a new challenge for these immigrant populations, directly or indirectly through the tensions between the ethnic groups that it helps to generate [@coates2020Covid19]. It is therefore necessary to understand how this pandemic affects these immigrant populations differently and the native populations in Quebec. -->

<!-- The coronavirus pandemic has affected nearly 100,000 people in Quebec and has resulted in more than 6,000 deaths. This makes it the worst affected province in Canada and one of the worst affected regions in the world. Although the majority of these deaths took place in homes for the elderly, and therefore affected this segment of the population more, its overall influence on individuals is not to be overlooked. In fact, in addition to the direct consequences of the pandemic, the measures taken by various governments around the world are also not without consequences on families. Several studies have thus shown excess mortality in ethnocultural minority populations [@bertocchi2020Covid19], higher unemployment, greater loss of income and negative consequences for children and families in several countries. -->

<!-- This differentiated effect can be explained in different ways. On the one hand, in terms of the direct consequences of the pandemic, the situation of precariousness and greater poverty among immigrants exposes them more to the more harmful consequences of the disease on their state of health. Likewise, immigrants often work in jobs where social distancing is difficult to enforce. On the other hand, indirectly, the solutions to the crisis affect immigrants and natives differently. The complete shutdown of the company with its set of adjustments has greatly impeded the employability of immigrants, especially newcomers who have not yet grasped the workings of society and who cannot benefit from state subsidies. But, it is also shown that these effects are not uniform on the whole of the immigrant population, itself, very diverse. -->

<!-- Faced with the pandemic, the governments of Canada and Quebec have implemented a number of measures to reduce the impact of the pandemic. These policies can be broken down at two levels, direct support to families, including the Canadian Emergency Benefit, which can provide employees and self-employed workers affected by Covid-19 with a financial benefit of up to $ 2,000. On the other hand, the government supports many companies to keep their employees or supports them directly when the revenues from their activities have fallen considerably. While these measures allow families to cope better with the crisis, the fact remains that the changes brought about by this crisis can affect other dimensions of life. How these measures make a difference in the face of the pandemic remains to be seen. -->

<!-- This study mainly aims to understand the family consequences of the pandemic on immigrant and native Quebec populations. Therefore, we will seek to analyse in what ways its consequences differ according to the region of origin of immigrants, length of residence, age and sex. -->

\newpage
