---
knit: bookdown::render_book
editor_options: 
  markdown: 
    wrap: 80
---

# Methodology

## Data

The data for this study come from an original collection of biographical data on
immigrants and the native population of Quebec to analyse their participation in
Quebec society in various fields (social, economic, cultural, etc.). The
immigrant population is limited to recent immigration that has taken place over
the past 15 years. This survey has several components that retrace the life
course of individuals over a long period of time. The pandemic component uses a
reduced version of the [harmonized questionnaire on exposure and the impact of
Covid19 on the family
(CEFIS)](https://www.phenxtoolkit.org/toolkit_content/PDF/CPTS_CEFIS_FullSurveyEng.pdf).
The questions are divided into three parts, on exposure to the disease, its
consequences and the benefit of the policies put in place by both the federal
and provincial governments. The other parts of the questionnaire focus on the
characteristics of the respondents, their immigration history, their educational
and family background. In short, it is a detailed questionnaire that covers the
life of immigrants from birth and especially over the past 15 years. The data
collection lasted three months, from August to November 2020. In total, 1,500
people were surveyed, including around 1,000 immigrants and 500 natives
throughout Quebec.

### Dependent variables

We distinguish three groups of dependent variables:

**1. Disease exposure variables**: these are measured by six questions that seek
to document whether the individual through work or a family member may have been
exposed to the disease. For example, it is asked if a family member has had
symptoms of the disease, or if a member has been hospitalized due to the
contraction of the disease.

**2. Variables on the family consequences of the disease**: we measure three
dimensions of consequences. The first group of measures assess the consequences
on accessing ressources by the respondent or any member of his family. The
second group of measure assess whether the respondent or any family member have
difficulties to perform usual duties toward any member of the family. Finally,
the last group of measures measure the consequences of the pandemic on
employment and income of any family member.

**3. Variables on government assistance**: Finally, government support is
measured by the following two questions that assessed whether the respondent or
any family member has benefited of the temporary assistance for workers from the
Government of Quebec (PATT) or of the Canadian Federal Government Emergency
Benefit (CEP). The table XXX in the apendix presents the full set of indicators
of the dependents variables

### Main independent variable

The main independent variable is immigrant status coupled with visible minority
status. This variable takes the following modalities: 1 if the respondent is a
non-racialized native, 2 if he is a non-racialized immigrant, 3 if he is a
racialized immigrant, and 4 if the respondent is a racialized native or an
immigrant who has not answered the visible minority question. The other
variables in the analysis are: age, sex, length of residence, minority status,
size of social network.

## Analysis methods

We use two main methods of analysis, a descriptive method and an explanatory
method. In the descriptive method, we consider each of the independent variables
in isolation and describe how they vary depending on the main independent
variable. The explanatory methods goes further by assessing whether the effect
remain when controlling for other covariates. Thus, by controlling for the other
explanatory variables, we determine the effect of immigrant status on exposure
to the pandemic, on its consequences and on the fact of benefiting or not of
government assistance. In a second series of modelling, we assess whether the
effect that we observed varies by the immigrant's length of residence or by
marital status. We use either a logistic regression on the outcome variables
that are binary and an ordonned logistic regression for the outcome that are
measure with a 5-point Lickert scale.
<!-- PUT THIS AS A LIMITATION IN THE CONCLUSION
To be able to benefit from government benefits, one must meet a number of conditions, including the loss of job due to Covid-19. As a result, the beneficiaries are not the general population but those who have lost their jobs and this may itself be due to immigrant status. Thus, for model 3, we will use Heckman's models by first estimating the fact of having lost or not a job and then, the fact of receiving or not the government benefit.
-->

\newpage
