---
knit: bookdown::render_book
editor_options: 
  markdown: 
    wrap: 80
---

# Références

<http://www.oecd.org/coronavirus/policy-responses/what-is-the-impact-of-the-covid-19-pandemic-on-immigrants-and-their-children-e7cbb7de/>

Guttmann A, F. et al. (2020), COVID-19 in Immigrants, Refugees and Other
Newcomers in Ontario: Characteristics of Those Tested and Those Confirmed
Positive, as of June 13, 2020, ICES, <http://www.ices.on.ca>.

Hu, Y. (2020), "Intersecting ethnic and native--migrant inequalities in the
economic impact of the COVID-19 pandemic in the UK", Research in Social
Stratification and Mobility, Vol. 68, p. 100528,
<http://dx.doi.org/10.1016/j.rssm.2020.100528>.

Mcginnity, F. and G. Kingston (2017), "An Irish Welcome? Changing Irish
Attitudes to Immigrants and Immigration: The Role of Recession and Immigration",
The Economic and social review, Vol. 48/3, pp. 281-304,
<https://www.researchgate.net/publication/319670153_An_Irish_Welcome_Changing_Irish_Attitudes_to_Immigrants_and_Immigration_The_Role_of_Recession_and_Immigration>
(accessed on 2 October 2020).

Raisi-Estabragh, Z. et al. (2020), "Greater risk of severe COVID-19 in Black,
Asian and Minority Ethnic populations is not explained by cardiometabolic,
socioeconomic or behavioural factors, or by 25(OH)-vitamin D status: study of
1326 cases from the UK Biobank", Journal of Public Health, Vol. 42/3, pp.
451-460, <http://dx.doi.org/10.1093/pubmed/fdaa095>.

Apea, V. et al. (2020), Ethnicity and outcomes in patients hospitalised with
COVID-19 infection in East London: an observational cohort study, Cold Spring
Harbor Laboratory, <http://dx.doi.org/10.1101/2020.06.10.20127621>.

Bertocchi, G. and A. Dimico (2020), "Covid-19, Race, and Redlining", IZA
Discussion Paper, Vol. 13467,
<https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3648807> (accessed on 22
September 2020).

Brun, S. and P. Simon (2020), "Inégalités ethno-raciales et coronavirus", De
Facto 19.
