---
title: "COVID-19 Disparities in Quebec (Canada)"
author: "V. Adjiwanou, G. NGalé, S. Lardoux, N. Zahedinameghi"
date: "`r format(Sys.Date(), '%B %e, %Y')`"
present_to: "Vissého Adjiwanou"
type: "Article"
knit: bookdown::render_book
subtitle: A Comparative Analysis of Exposure Risks, Consequences, and Access to Resources among Immigrants and Natives
site: bookdown::bookdown_site
bibliography: "library.biblatex"
csl: apalike-uqam.csl
editor_options:
  markdown:
    wrap: 80
    fontsize: 12pt
documentclass: article
link-citations: yes
institute: Université du Québec À Montréal and Université De Montréal
abstract: "The immigrant population is one of the most vulnerable in Canada, with a relatively high risk of unemployment, a low social support system, and linguistic barriers. However, their experiences with public health interventions during the COVID-19 pandemic have not been adequately explored. The purpose of this article is to analyze Covid-19 exposure risk and its family implications for both natives and immigrants in the province of Quebec. Additionally, we analyze immigrants' access to government aid and compare it to their native-born counterparts. The study consists of survey data collected from 1,000 immigrants and 500 non-immigrants Quebecers between August and November 2020. Our descriptive and exploratory analysis reveals significant differences between the two groups regarding exposure risk, family consequences, and access to resources. We conclude that the current pandemic exacerbates health disparities in the province, with particularly dire repercussions for immigrants' families. We also discuss several socio-cultural strategies to mitigate inequality and recommend policies to address the needs of vulnerable populations."
---

```{r}
# Importer package
library(dplyr)
library(tidyverse)
library(summarytools)
library(readr)
library(questionr)
library(rcompanion)
library(pander)
```

```{r}
# Set numero graphique
no_graphic <- -1
```
