---
title: "Expérimentations"
author: "Théa Carlier"
date: "2023-05-02"
output: html_document
---

```{r}

rm(list = ls())

library(tidyverse)
library(summarytools)
library(srvyr)
library(survey)
library(ggpubr)
library(writexl)
library(haven)

Base_Trajipaq_Finale_Ok <- read_dta("~/GitHub/Projet_Immigration_Trajipaq/Data/Base_Trajipaq_Finale_Ok.dta")

```

# Régression logistique entre deux variables numériques (VD = nominal dichotomique, VI = ratio)

```{r}
#transformation de la variable COV12 (Nous avons eu de la difficulté à obtenir des soins de santé quand nous en avions besoin)
Base_Trajipaq_Finale_Ok <-
  Base_Trajipaq_Finale_Ok %>%
  mutate(COV12_2 = case_when(
         COV12 == 1 ~ 0,
         COV12 == 2 ~ 1,
         COV12 == 98 ~ NA,
         COV12 == 99 ~ NA,
    ))

#soustraction des réponses (la même année que la résidence permanente, je ne sais pas et je ne souhaite pas répondre)
Base_Trajipaq_Finale_Ok <-
  Base_Trajipaq_Finale_Ok %>%
  filter(Q14I < 2019)

#régression logistique entre COV12_2 (VD) et Q14I (Depuis quelle année vivez-vous au Québec)
model1 <- glm(formula = COV12_2 ~ Q14I, family = "binomial", data = Base_Trajipaq_Finale_Ok)
summary(model1)

#les résultats indiquent que le risque d'erreur alpha est supérieur à 5%. Conséquemment, la relation étudiée n'est pas significative.
```

# Représentation graphique de la régression logistique

```{r}
#représentation graphique de la régression logistique
ggplot(Base_Trajipaq_Finale_Ok %>% filter(!is.na(COV12_2), !is.na(Q14I)), aes(x = Q14I, y = COV12_2)) + 
  geom_point() +
  stat_smooth(method = "glm", color = "blue", se = FALSE,
    method.args = list(family = binomial))

#résultat invalide car COV_2 est une variable numérique discrète
```

## Un autre test pour la régression logistique

```{r}
  
Base_Trajipaq_Finale_Ok <-
  Base_Trajipaq_Finale_Ok %>%
  filter(COV14 < 98) %>%
  mutate(COV14 = case_when(
         COV14 == 1 ~ 0,
         COV14 == 2 ~ 1,
  ))

model3 <- glm(formula = COV14 ~ Q14I, family = "binomial", data = Base_Trajipaq_Finale_Ok)
summary(model1)

ggplot(Base_Trajipaq_Finale_Ok %>% filter(!is.na(COV14), !is.na(Q14I)), aes(x = Q14I, y = COV14)) + 
  geom_point() +
  stat_smooth(method = "glm", color = "blue", se = FALSE,
    method.args = list(family = binomial))
```

# Analyse de la variance (ANOVA) entre deux variables numériques (VD = ordinal, VI = ratio)

```{r}
#création d'un dataframe regroupant les variables COV35 (Votre bien-être émotionnel - humeur s'est beaucoup, un peu ou pas amélioré) et Q14I.
df_1 <- Base_Trajipaq_Finale_Ok %>%
  select(COV35, Q14I) %>%
  drop_na()

#ANOVA entre COV35 (VD) et Q14I (VI)
model2 <- aov(Q14I ~ COV35, data = df_1)
summary(model2)

##les résultats indiquent que le risque d'erreur alpha est supérieur à 5%. Conséquemment, la relation étudiée n'est pas significative.
```

## Code alternatif pour l'analyse de la variance

```{r}
#l'utilisation de pipes évite de créer un dataframe.
Base_Trajipaq_Finale_Ok %>%
  select(COV35, Q14I) %>%
  drop_na() %>%
  aov(Q14I ~ COV35, data = .) %>%
  summary()
```
